### ISSUE TITLE
Clarify in the docs that tzdata is installed automatically for Windows users

### ISSUE THREAD

**Issue by jackfirth** [97jaz/tzinfo#5]
This section of the docs:

> UNIX systems usually come with a compiled version of the IANA database (typically in /usr/share/zoneinfo). tzinfo will use the system’s database if available. However, if the tzdata package is installed, that will be used instead. Since Windows systems do not come with a zoneinfo database, Windows users must install tzdata to use tzinfo.

...seems to imply that Windows users must explicitly install `tzdata` themselves in order to use `tzinfo`. But the platform-specific dependency in `tzinfo`'s `info.rkt` file takes care of that automatically. It would be clearer if the docs explicitly specified that Windows users don't need to do any work beyond installing `tzinfo`.

**Comment by 97jaz** [comment]
Good point
